import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="middle">
        Please{" "}
        <span style={{ color: "#22D3EE" }}>
          <Link href="Home">click here</Link>
        </span>{" "}
        to navigate to home
      </div>
    </div>
  );
}
